### ISSUE TITLE
Credit card form: back navigation empties cart

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#100]
When navigating back from the Credit card from you find the Shopping Cart empty. People might notice that they misplaced their CC and want to pay by bank (or later...).

**Comment by inbaz** [comment]
That's not possible at this state. I'd like to insert a thank you page and tell the purchaser that he got all payment infos per mail and he will be able to create a password, login and change the payment type. The order is already made at this step. My opinion is that it's not a valid reason to give back the tickets which are already bought. What do you think?

**Comment by jackcaveman** [comment]
This is after pressing [buy now] on the check page, but before you pres [pay now] on the CC form. Before entering your CC details you made up your mind and want to go back.

**Comment by inbaz** [comment]
So, make a suggestion which includes the possibility to go back to the order details but I think it should not be possible to change the shopping cart anymore. Changing the paymenttype is no problem I think, but a workflow is needed.

If I fill up the shopping cart with existing data I think somebody could just clear the shopping cart and reorder what he wants, which results in a duplicate order.

**Comment by jackcaveman** [comment]
Lock the contents of the cart when you proceed to the CC form. 
Unlock the contents when you navigate back (or press cancel). Juggler can add/delete products change paymentType (everything).
When CC transaction is successful: reset cart.

(hack suggestion: popup with the text: "When you proceed to the next Credit Card payment you can't make changes to your order anymore. Do you want to proceed? [yes/cancel]")

**Comment by smadamit** [comment]
@inbaz I didn't get your point. What is the problem. Why do you clear the shopping card after entering the payment type credit card?

My opinion: You give the buyer much flexibility of navigating through the checkout steps #62 If you do so, please give the possibility to change everything at every step. If you don't want or can't do so avoid navigating back to the shopping card, and give a tip before entering credit card form, that you can't make changes to your order anymore. Same suggestion like jackcaveman.

**Comment by inbaz** [comment]
I get your point and I like it to be able to change the payment type whenever you want. We need a what happens when list with step by step of what the purchase can do and what he should not be able to do. At any step there needs to be the point where it's not possible to change the shopping cart anymore. This includes a decision what happens with unpaid orders. Let's talk about it on the next skype meeting.
@smadamit Could you please take this ticket as a point for the agenda?

**Comment by smadamit** [comment]
Yes I add all open issues to be discussed to the agenda of our skpye con

**Comment by smadamit** [comment]
same issue posted: #141

**Comment by smadamit** [comment]
we need a solution for that issue

**Comment by inbaz** [comment]
back navigation redirects now to an order overview page where the user can at the moment only get some infos about the order and later the user will be able to get payment info, restart credit card payment, resend/download eTickets. Since the authentication to this page is only working through a hash which is save in the order the user cannot change the order except maybe the payment type. On this page the user has no possibility to change participant details or move a ticket to another person.

**Comment by smadamit** [comment]
tested in v0.2.36
- it works if you use the back navigation of the browser history.back()
- it does not work if you click on the menu "My Shopping Cart" or any other menu-link. I guess there will be users doing so. But you are getting an email with a link where you can continue your payment. That works for me.

I will do further testings on that issue.

**Comment by smadamit** [comment]
@inbaz what do you think? See the last comment...

**Comment by smadamit** [comment]
retested in 0.2.45

It works for me. For going live it's enough.

For future a nice to have:
- fix: it does not work if you click on the menu "My Shopping Cart" or any other menu-link. I guess there will be users doing so.

**Comment by inbaz** [comment]
At this step the order is finished and the user can make a new order. They got all needed information via mail, then they need to navigate through other ways to their order. I cannot divide if the user will go back to the currently bought shopping cart or want to make a new order and check if the shopping cart is empty again.

For me this is fixed.

**Comment by smadamit** [comment]
you are right.
