### ISSUE TITLE
overlay for legal terms and conditions page

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#16]
It now leaves the checkout page. Better to have an overlay showing the Term and Conditions with the scroll bar.
Also add a download link to the PDF version of the TaC. (legal requirement)

**Comment by smadamit** [comment]
I think the easiest way is to give a download of the pdf in a new window. By the way at the moment we do not have legal terms. See my email yesterday -> open do to for EJA and EJC.

**Comment by inbaz** [comment]
If there's a link to go back to the checkout on top of terms and conditions this will work, too.

**Comment by smadamit** [comment]
@inbaz  The legal terms and conditions will be available on prereg.eja.net and www.ejc2015.org. For me it's fine if you link to info/terms like you are doing now, but with a back-link to the checkout. This would solve also #191, because I would not send the legal terms attached as PDF, but as link to one of the sites. Do you agree?

**Comment by smadamit** [comment]
Works for me as it is
