### ISSUE TITLE
wrong prices for deadlines

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#179]
preregpp 0.2.32

see the setting in admin panel:

![screen-admin](https://cloud.githubusercontent.com/assets/1533081/6648023/16244212-c9d5-11e4-8882-7d620c0e1916.png)

result in frontend:

![screen-front](https://cloud.githubusercontent.com/assets/1533081/6648025/19d708f4-c9d5-11e4-966f-8a89401d441e.png)

**Comment by inbaz** [comment]
The system found all prices correctly. The real problem was that the system was iterating through all agegroups. So for those which are not displayed in the price matrix the price found was no agegroup, no deadline, which is correct. I filtered the agegroups in the frontend, so this should be fixed in 0.2.33

**Comment by smadamit** [comment]
no not fixed. tested in preprod 2.36

**Comment by smadamit** [comment]
Hä... Now it works preprod 0.2.36
