### ISSUE TITLE
not able to do anything after mysql-error

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#207]
tested in preregpp v0.2.38

After the bug in #206 nearly every request fails with a blank page. After resetting the shopping card (destroying the session) it works. How should we handle such a situation. A common user will not be able to handle this situation.

![unbenannt](https://cloud.githubusercontent.com/assets/1533081/6711935/42d84886-cd8a-11e4-9245-f936712a3e81.png)

**Comment by inbaz** [comment]
The user will give up and after an hour the session will be destoyed automatically. I cannot reproduce what you did. Looks like a mixture of backend and frontend stuff. Since normal users do not have access the the backend this is no problem for frontend users if the backend triggered this problem.

At the end we cannot completely exclude that and then we need to trust on peoples communication skills.

**Comment by smadamit** [comment]
the bug was from David, not me. So it has nothing to do with the backend. I push the bug to milestone SecondLife.
