### ISSUE TITLE
[fix before test] Payment Types not working

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#3]
During checkout, none of the payment types can be selected except "Bank Bruneck".

**Comment by inbaz** [comment]
Like we said in the call the other payment types are the example types which do not have a correct paymenttype_id and therefore are unavailable in the database. I just removed these examples in git master.

**Comment by jackcaveman** [comment]
Do you don't want them tested at this stage?

**Comment by inbaz** [comment]
Hopefully I'll be ready at sunday, then we can test them. But I don't 
know if everything is working like expected. The testers should know 
that this is a pre alpha version and some functions are not implemented 
and some function are not yet functioning correctly. Therefore the 
testing matrix is important for this step. Because there we listed what 
should work and what's missing at the moment. I will add some points to 
that list today because yesterday I introduced some new controllers.

In consideration of the fact that there is really less time to get this 
system ready we should start testing in a early state and the testers 
should know that they need to be patient and not give up on the first 3 
errors they get. I'm fast, but I'm not familiar with doing any magic. :) 
I'm at the point where I'm getting blind on what is the next feature 
that's needed to get a fully functioning system. That's the point where 
the testers come into this project. The should not only test the 
existing function but I wish they come over with requests like: I miss 
the possibility to do X on page Y. This info is put into a ranking where 
I try to work from blocker or mission critical to nice to have. I hope 
this is making the sort of testing at the moment a bit clearer.

Am 19.02.2015 um 09:22 schrieb jackcaveman:
> Do you don't want them tested at this stage?
>

**Comment by jackcaveman** [comment]
I understand what you mean, staring at all the possible modules to work on.
External input can get you bank onto track again.

That makes it bit more concrete. I will make the use cases as they are
expected to work. Then I can always indicate to the testers that some
features will break anyway, but for them to find out how and when ;)

**Comment by inbaz** [comment]
This is fixed since bank account payment is working now. Other payment types are wip.
