### ISSUE TITLE
cookies warning hides menu bar

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#324]
One tester did not see the menu bar, since she does not confirm the cookies warning. As a consequence she was not able to navigate. I don't know how we should solve this issue. Or just wait if there are more people out there with the same issue?

**Comment by christianbross** [comment]
I agree that this can happen - I saw it myself with an unexperienced user - just didn't read what was on the screen, simply ignore the text at the top, and of course was wondering how to navigate around
so obviously it's not a "once in a million" problem, 
idea: can we make the "accept cookies" text blink so that people can't simply ignore it?

**Comment by inbaz** [comment]
I changed the css code for the next version so the warning just moves the main menu down and if the cookie warning is accepted it gets hide.

**Comment by smadamit** [comment]
Sounds good. I will recheck in the new version.

**Comment by smadamit** [comment]
tested in 0.3.23 -> nice
