### ISSUE TITLE
separate onsite-reg and cash-desk

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#327]
separate onsite-reg and cash-desk -> details have to be discussed...

**Comment by inbaz** [comment]
What are the basic reasons for that?

**Comment by smadamit** [comment]
see my mail...

**Comment by inbaz** [comment]
The main question here is: Do the spontanious participants need to be put into the system?

**Comment by smadamit** [comment]
In my opinion: Yes would be nice. But it's not a must have.

**Comment by smadamit** [comment]
We will discuss later again

**Comment by inbaz** [comment]
As long as the question if spontanious participants needs to register through the system or not is not answered this can not be solved.

What differences do we really need for a cash desk? The cash desk volunteer needs rights to set a order which uses the payment type "cash" to status paid. I think in this case paid and shipped will be the same status because the volunteer gets the money and the participants their tickets. That's it.

If this is the main part of this issue it should be included into OnsiteReg.

**Comment by smadamit** [comment]
skype -> OK
