### ISSUE TITLE
Make "buy now" button more visible on last order page

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#343]
Using a macbook as prereg device on BJC, the "buy now" button (and the "agree to terms and conditions") isn't visible without scrolling.

Some people were confused if thy were already finished (maybe because it's not their macbook and the scroll bars are hidden). However, they might have stopped there thinking that they had registered.

=> Is it possible to have the buy now button (with terms and agreement) visible at the page bottom all the time (and still be able to scroll the rest of the page)? CSS magic?

**Comment by inbaz** [comment]
The users should read the whole page, check if the order is fine and after that press the buy now button. So I think putting the buy now button at a more present place will lead to more unwanted purchases. Disabling the buy now button until the user scrolled completely down with a speaking tooltip would be a possibility but I think this issue is rather nice to have than prio 2, or not?

**Comment by smadamit** [comment]
I would even close this issue
