### ISSUE TITLE
admin/statistic enhancements

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#392]
For a better performance split the statistics. I don't know what are the run times of the blocks, so that's just an arbitrary suggestion:
- orders
- participants and products
- Product Variants
- payment types
- As a new statistic: countries where the participants are coming from

**Comment by jackcaveman** [comment]
Probably you guys have been thinking and working on this already. 
To give the EJC team more insight about the current financial status. It's good to know the difference between real money in the accounts and sold in the ERS. Because know I do not know how much more banktransfers I can expect now.

Maybe include some extra calculations in the stats page? My suggestion would be:
1) Banktransfers: Total amount || refunded
2) Creditcard: Total amount || refunded
3) Check: Total amount || refunded
====
4) Summary:  Total amount || refunded || cancelled
5) (current?) Netto amount

For this to work and compare with finances, there needs to be a "filter" function to select a date range (e.g. 01 apr to 07 may).

**Comment by inbaz** [comment]
refund information can only be inserted into the ers statistics if they are anywhere in the system. But they aren't, yet.

I do not understand the need of the date range filter. Could you be a bit more presize on how is done with that filter and which data ist filtered with that?

Since there will ever be special cases for volunteers, orgas, dealer and people from the city in which the EJC takes place it's not really possible to have an exact calculation of what's sold through the system and what's really on the bank account. So all numbers out of this system needs to be interpreted in the right context and there on no way around the direct communication of the EJA treasurer and the EJC Core Team on how much money is present and can be worked with for the EJC.

So what we want to do in this ticket is to find out which statistic parts we need and if there are statistics which needs to be on one single page and which we can put on separate pages to not load nearly every database entry from the database to generate the statistics.

**Comment by inbaz** [comment]
@Bone008 I moved the ticket to you because here is the information on how to change the statistics. There are some starters already in the code. Maybe we need to rediscuss the site structure of the single pages.

**Comment by inbaz** [comment]
merged into 0.3.75

**Comment by smadamit** [comment]
0.3.75 -> OK
