### ISSUE TITLE
SPF Record

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#41]
Staffan have to do the SPF Record in the DNS-system

**Comment by inbaz** [comment]
Since you're using gmail for eja.net mails there needs to be the according spf record like described here: https://support.google.com/a/answer/178723?hl=de&ref_topic=2759192

In addition we want to allow the prereg.eja.net server to send mails from @eja.net email addresses. ip4: 82.165.142.22 should do that.

So the record should look like this:

IN TXT v=spf1 include:_spf.google.com ip4:82.165.142.22 ~all

**Comment by staffanu** [comment]
I have now set up SPF records for prereg.eja.net (and also preregpp.eja.net -- I guess there is no need for that).  Mail to the users prereg@prereg.eja.net and prereg@preregpp.eja.net (and also postmaster etc) should end up in the mailbox prereg@eja.net. The current routing might or might not be acceptable. I think it should work, but we probably want to add a secondary mx.

**Comment by staffanu** [comment]
SPF for eja.net is implemented.

**Comment by smadamit** [comment]
very nice! @inbaz can you please implement, than we can do the first tests with the new mailserver.

**Comment by inbaz** [comment]
done as of 0.2.38

**Comment by smadamit** [comment]
tested in 0.2.39 -> OK
