### ISSUE TITLE
why is the credit card return array NULL?

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#535]
see admin/order/detail/706 in prod

**Comment by inbaz** [comment]
The ticket was ordered and since this is a credit card payment, payment has been tried but iPayment answered with no data. Let's have a look after the auto-matching if there is a payment for this order in the csv export.

**Comment by smadamit** [comment]
Then this is a crucial bug. The order 3489FU71 should not be in status paid!

![screen](https://cloud.githubusercontent.com/assets/1533081/8248972/78e5b7a0-1665-11e5-84e8-febefc4323f8.png)

**Comment by smadamit** [comment]
Can you please check in the database if there are more orders like this: credit card with return array NULL.

**Comment by inbaz** [comment]
There are 66 cases where the system didn't save the payment details in 50 orders. I don't know why this happens, yet. But the paid status is correct, because this status is set by a request which is only made if the iPayment system has a successful payment.

please delete the screenshot above it contains sensible data which should not be accessible for everybody.

**Comment by smadamit** [comment]
"But the paid status is correct..." -> Than I would suggest, that this is not a hotfix. We have to fix it later, but it's not important yet. Do you agree?

**Comment by inbaz** [comment]
We implemented the payment details before the whole bank statement stuff. Maybe it's a better idea to change the structure to add a bank statement instead of just these payment details. But that can be made later. I agree.
