### ISSUE TITLE
Use Entity\Log when ship/unship an item

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#605]
An example can be found in the ItemController of the Admin module. Please simply add a log entry with "item $item->getName() of package $package->getCode()->getValue() shipped" or unshipped. If you have a good idea on how to make the entries for shipped and unshipped more different to be able to search for them, do so.

**Comment by Bone008** [comment]
Done in f-onsite.

To identify different actions, we could add a simple string field called "type" to the Log entity, which would for example contain "ship_item" or "unship_item".

However, I think a much more common use case would be to search for the package code and list all logs recorded for it. So a simple fulltext search filter through logs should be enough, which also (almost) can be used to filter for shipped/unshipped.

It's a shame that "shipped" is fully contained in "unshipped" though, so that might make things harder than necessary ;)

**Comment by inbaz** [comment]
Since the Log will be available all over the system I thought about a json structure to be able to save several meta data to the Log Entities data field. In this case we need the Package Code but I don't know if we need that in every case. Let's do it simple. If you think the code would be a great idea in this case, implement it and we'll use it as is but set it to nullable=true to be able to let it empty.

Let's do a typo for the unship status and write shunip to be able to do a search for only unshipped items.
