### ISSUE TITLE
make products with no deadlines possible

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#648]
Hi,

At the moment every product has a deadline.

We want products in there without a deadline, when no deadline applies and/or the prices won't change.

(I don't know what to write at step 3, sorry)

**Comment by inbaz** [comment]
If you add a price with no Deadline this price is used when no other price could be found. This should solve the problem, or not?

**Comment by davebarnesy** [comment]
I entered the T shirts without a deadline and with a single price.  I wonder if the problem here is just that every product says 'the prices will go up on [some date]' above the prices?  

So maybe we should just make the system hide that txt when it's not needed (when there's a single price)?  Or do we need to do something with another deadline for those products?

**Comment by inbaz** [comment]
Ah, so this is a frontend issue. The problem is that on the product page the info is shown that prices will raise at the next deadline.

**Comment by inbaz** [comment]
Which of the above points is open at the moment? Is there anything to do to solve this issue?

**Comment by jolieno** [comment]
The deadlines are still visible with seperate galatickets and daytickets, where no prices changes will occur. But i don't think this is a issue, i don;t mind.

So yes, i'll close this issue.
