### ISSUE TITLE
Most orders have a NULL paymentType

### ISSUE THREAD

**Issue by odegroot** [inbaz/ers#693]
I'm not sure what the intended behaviour is here. Andi, can you say what *should* happen here?

![image](https://cloud.githubusercontent.com/assets/807291/12536577/be3e8ebc-c2a9-11e5-8d72-44ce232ff413.png)

This also breaks the *Pay via Bank Transfer*-page.

![image](https://cloud.githubusercontent.com/assets/807291/12536593/ff30ef50-c2a9-11e5-9120-bc0e59d8b86a.png)

**Comment by inbaz** [comment]
Intended here is that the specific id of payment-type is saved in this field. Looks like the payment type is not correctly saved in /order/payment when pressing continue. I thought the /order/checkout checks if the current order holds a payment type and gives an error message if not.

**Comment by inbaz** [comment]
I just checked the workflow. So I can be that there are many orders inside of this sql dump which are not correct at all. At my check the payment type was saved correctly. There is a status_id in the order table and if the status_id links to the status "order pending" these orders are not saying anything, because they are there because a tester stopped ordering these tickets. Once the order status is set to "ordered" the order needs to be fully configured and complete with all information that's needed for payment matching and e-ticket delivery.

For this error please check if you're missing the calcFee methid in the \ErsBase\Entity\PaymentType class. This should be there. If not please copy it from oldEntity.

**Comment by odegroot** [comment]
So basically, you're saying *working as intended* for the NULL-values in the `order`-table, and *cannot reproduce* for the error *Pay via Bank Transfer*-page?

If I understand you correctly there, then I vote to just close this issue. No point spending time on bugs that don't occur on the real server.

Presence of a `calcFee` method in `\ErsBase\Entity\PaymentType` is irrelevant, since the `$paymentType` variable is `null`, not some instance without a `calcFee` method.

**Comment by inbaz** [comment]
Yes, exactly that's what I ment.
