### ISSUE TITLE
A date in the 'payment reminder email' is not correct

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#759]
A date in the 'payment reminder email' is not correct.

> Dear Josef,
> 
> you registered for the EJC at 27.02.2016 and we hope you're looking forward to it. We haven't sent you an e-ticket yet, because we haven't received payment for your order.
> 
> Please do one of the following until **20.07.2015** at the latest.
> 
> Please pay your order at... 

Let's change this date to 20.07.2016.

**Comment by kskwared** [comment]
Suggest priority 2 because users will know that the event is in 2016

**Comment by inbaz** [comment]
Please do not use functions that are not prepared for EJC 2016, yet. I looked at the e-mail communication and what was needed here was just the resend confirmation function. The payment reminder is ment for reminding people if they have not paid their tickets for a very long time. Last year we implemented this function, but we never used it. So please use the resend confirmation function.

**Comment by jolieno** [comment]
Wouldn't this function be perfect to use after the first fase has ended (or after any fase change)? At the moment lot's off people have booked a ticket, but not paid for it yet (we're over a 1100 booked tickets, about 500 are paid for at the moment). 

In the confirmation email which the system sends out, it says people have to pay in 14 day's after booking. We're not strick about this, which is fine. But if we can manage to have the E-tickets prepared for sending out in april. I think it would be nice to implement this function. Because this email is more clear about paying, than just sending out the confirmation mail again.

What do you think?

For now, i will tell the pre reg coordinator not to use this function.

**Comment by inbaz** [comment]
Depends on the context the mail is used. If you're already talking to a specific person whose payment type was changed, this is not the correct e-mail to send out for the new information about the changed payment type. I think that was exactly the case for what this ticket was opened.

I already created #753 to create a centralized e-mail template to make all those e-mails look the same, like same header, same colors and so on.

The numbers that you provide are not correct, we already mentioned that in our last skype call. I think about the half have really booked a ticket. Most of the orders are not in status paid because the matching of the bank statements is not in place, yet.

As of we're not strict with the payment form last year we learned that it's a way better strategy to make marketing to get more and more people register than annoying thos who already did with a payment reminder. From now until 31st March it would be a good idea to make facebook posts on every weekend.

Since sending a payment reminder is not mandatory in our case I would rather concentrate on bank statment matching and e-ticket generation than on this e-mail. It's not just the preparation of the mail that needs to be done but also a script that filters out ordered but not paid orders to be able to send such a payment reminder out.

**Comment by jolieno** [comment]
Hi,

i'll try to respond by revering to the above writen remarks;

alinea 1: 
Yes, you are right here. This mail was send out just for this. The pre reg coordinator now knows she should make a seperate/specifik email for this and not using the ERS system for this jet.

alinea 2: great.

alinea 3:
My numbers are based on the information we got from jasper. At the moment over 65.000 euro has been transfer to the bankaccount. Wich is +/- 500 sold tickets (probably a bit less since t-shirts are also included). Which is a great amount, i say so my self :+1:  

Alinea 4
I think this (how strict we want to be with the payment, what does this mean for the different fases, etc.) is something we need to discuss together with the EJA to form a vision about this. And than make a plan how (and if) we want to deal with it. @philip-n what do you think?

Alinea 5:
Yes, concentrate on the bank statment matching and e-ticket generation!
