### ISSUE TITLE
Detail view of pending orders without payment type is not rendered correctly

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#826]
### Current status:

The detail view page of pending orders without a payment type does not render correctly. HTML markup stops after the the buyers name is printed (in the "Payment Detail"-div). This also break page rendering.

Examples:
- https://ejc2016.ers.inbaz.org/admin/order/detail/187 
- https://ejc2016.ers.inbaz.org/admin/order/detail/828
- https://ejc2016.ers.inbaz.org/admin/order/detail/577
### Expected result:

Correct display of "No payment type set" and correct rendering of page.
### Probable cause:

Incorrect handling of unset (?) payment type around line 275 of https://github.com/inbaz/ers/blob/master/module/Admin/view/admin/order/detail.phtml

**Comment by inbaz** [comment]
This year it's new that we have all "order pending" orders in the database. These are shopping carts that has been started but never have been bought. Therefore they do not have information like payment type or buyer or some other fields set.

Since nobody will ask for such a order there is no interaction needed on the order detail page. This is a bug, but rather fixing the issue I would filter the orders in "order pending"-state out of the search results.

**Comment by philip-n** [comment]
Just checked: For all three examples I listed above, there is indeed a completed order with the same data (persons, ...) some hours or days later. I agree that hiding these is the best way to go.
