### ISSUE TITLE
Can't order "Weekticket Youth"

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#9]
Ordering a single "weekticket Youth" will show a disabled "buy now" button with the text "Please add all needed information to checkout." Also the "terms and conditions" checkbox is gone.

Adding a different purchaser does not resolve the issue.

Adding a T-shirt to the cart (unassigned) resolves the issue and makes the "buy now" button available again. 

n.b. When clicking the "buy now" button I get the same error as issue #8

**Comment by inbaz** [comment]
That's a general problem: I'd like to show products with a price of 0 
Euro, because maybe there is a need of counting cards for a show which 
does not cost anything. So there needs to be some general discussion for 
products with "no price".

At the moment you can buy this product because I'm checking not total 
sum == 0 anymore but item count == 0.

The exception error is fixed aswell.


Am 22.02.2015 um 19:22 schrieb jackcaveman:

**Comment by inbaz** [comment]
It's possible to buy products even if they cost 0€ now.

**Comment by jackcaveman** [comment]
Verified
