### ISSUE TITLE
admin/order/index

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#95]
why there are many orders where the purchaser has no name?

**Comment by inbaz** [comment]
Check in 0.2.8 from when the orders are. I added the timestamp of order creation. Maybe its because of an already fixed bug. I suggest, we delete them and look if there get in new ones without a purchaser.

**Comment by smadamit** [comment]
See my last 2 tests: H3HRDC12 and 7NYXPD58. In the list you can see my email, but not my name. Still open issue.

**Comment by inbaz** [comment]
Ah I see, this is because you have registered without firstname and surename set while registration. This is for security reasons. If I would save the purchaser info here into the database everybody has the possibility to change the data of a user which email address is known.

So the main issue is to
1. add the logged in user automatically to the list of persons
2. put in a message that tells the user that the already stored data was used and not the one which he gave in this pruchase process. Maybe in the payment information email.

I'd like to not have this information that a user with a specific email address already exists accessible to public.

**Comment by smadamit** [comment]
Ah OK. So same issue as #20?

**Comment by smadamit** [comment]
OK, if I use another email, it works: ARW6HD28.
Please fix it as you suggested.

**Comment by inbaz** [comment]
No it's not exactly the same since this issue includes the possibility for a user to change his name in his profile.

**Comment by smadamit** [comment]
Maybe let's talk to that at the next skype con

**Comment by inbaz** [comment]
@smadamit Please take it as an agenda point.

**Comment by smadamit** [comment]
same as #135
